### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by riverar** [vcsjones/AzureSignTool#72] opened 2019-04-27 08:18 UTC
Windows 10 1903, installed the tool, ran `azuresigntool` and got help text. `azuresigntool sign [...]` does nothing. No output. Tried 1.0.1 and 2.0.17 to no avail.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

cc @onovotny

**Comment by vcsjones** [comment] 2019-04-27 12:55
Hiya,

This is probably an issue with the tool not being as helpful as it could be. If you invoke the tool with no files to sign, it sees it needs to do no work, and just happily exits. I tried a command like this on 1903 and was able to successfully sign a file:

```
azuresigntool sign -kvu https://ci-test.vault.azure.net/ -kvc rsa2048-sha256-ci -kvi 77<redacted> -kvs 2y<redacted> D:\someprogram.exe
```

**Comment by riverar** [comment] 2019-04-27 18:06
Yeah, the help commands work but nothing else. Tried feeding it a file, some args, all args, just isn't outputting anything. Isn't crashing either. Very strange!

**Comment by vcsjones** [comment] 2019-04-27 18:09
Can you share the redacted version of how you are invoking the tool?

**Comment by vcsjones** [comment] 2019-04-27 18:16
Since the command line argument validation does not appear to be working right now (looking in to that...) I suspect you didn't try the right combination of arguments. The one above should work.

**Comment by riverar** [comment] 2019-04-27 18:16
```AzureSignTool sign -kvu "https://invalid.uri" -fd sha256 -kvi guid -kvs secret -kvc name -tr http://timestamp.digicert.com -td sha384 -vdiag -ifl test.exe```

**Comment by onovotny** [comment] 2019-04-27 18:19
Ifl looks wrong. That’s for a text file containing files to sign

**Comment by vcsjones** [comment] 2019-04-27 18:20
Try:

```
AzureSignTool sign -kvu "https://invalid.uri" -fd sha256 -kvi guid -kvs secret -kvc name -tr http://timestamp.digicert.com -td sha384 test.exe
```

**Comment by riverar** [comment] 2019-04-27 18:22
Still nada. Here's a bit less redaction if it helps.

```AzureSignTool sign -kvu https://abc.vault.azure.net -fd sha256 -kvi aaaabbbb-cccc-dddd-eeee-ffffgggghhhh -kvs "secret" -kvc "name" -tr http://timestamp.digicert.com -vdiag test.exe```

**Comment by vcsjones** [comment] 2019-04-27 18:24
I tried it with `-vdiag` and it seems like the tool currently doesn't like parameters it doesn't know what to do with and doesn't print anything, which is unfortunate.

**Comment by riverar** [comment] 2019-04-27 18:25
OK pass two, still nothing however this is why (lol, sorry):

```{"error":{"code":"Forbidden","message":"Operation \"get\" is not allowed by vault policy","innererror":{"code":"ForbiddenByPolicy"}}}```

**Comment by vcsjones** [comment] 2019-04-27 18:28
Hm, ok. Big take away for me here is that the command line interface needs to be a lot more helpful in troubleshooting.

1. When the arguments it wants aren't supplied.
1. When it gets an argument it doesn't know what to do with.
1. When there is a problem talking to AKV in a "non-happy-path" scenario.

For permissions, the following are required on the certificate:

1. Get,List,Verify,Sign under "Key permissions".
1. Get,List under "Secret permissions"
1. Get,List under "Certificate permissions"

**Comment by riverar** [comment] 2019-04-27 18:41
Thanks, looks good now. 👍 

One other nit to add to your list: The tool uses the color green for output, then forgets to revert to original configuration, tainting the console and subsequent command output.

**Comment by vcsjones** [comment] 2019-04-27 18:56
OK, I opened #73 and #74 to track improving both of those problems. Glad things are working now, sorry for a somewhat bad first impression.

I'll close this for now in favor of the new issues I wrote.

**Comment by Omzig** [comment] 2020-04-23 18:59
Is there anyway to put it in test mode and have it rough through each step but not sign? --debug is needed.

**Comment by riverar** [comment] 2020-06-05 04:50
Can we re-open this issue? AzureSignTool still continues to be black box when errors occur, wasting a bunch of my time. @vcsjones @clairernovotny

**Comment by vcsjones** [comment] 2020-06-05 04:52
@riverar fixes have been made but there hasn't been a release since, which I've actively been trying to get out this week. I'll re-open the issue and close when (what will probably be 3.0) is release. Apologies for the delay.

**Comment by Omzig** [comment] 2020-06-05 13:14
> @riverar and @riverar  fixes have been made but there hasn't been a release since, which I've actively been trying to get out this week. I'll re-open the issue and close when (what will probably be 3.0) is released. Apologies for the delay.

I have found that when you do not spell one of the properties correctly, it will not tell you that you spelled one wrong. you could miss a dash and then you just get blank/nothingness at the end. I switched over to the short version of the parms and that removed the copy and paste errors.

**Comment by wonderphil** [comment] 2021-02-05 17:41
Any update on this?

**Comment by wonderphil** [comment] 2021-02-05 20:17
Hi guys,
So while this doesn't help the fact we don't get outputs when running and something is not wrong, I have found that if I download the source and build it works.

The command I use to install the tool is 

```
set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
dotnet tool install --global AzureSignTool --version 2.0.17
```

then the command I run is

```
AzureSignTool.exe sign -du "https://wonderphiltech.io/" -kvu https://cert.vault.azure.net/ -kvt 111111-1111-1111-1111-11111 -kvi 22222-2222-2222-2222-222222222-kvs SECRET -kvc wonderphiltech -tr http://timestamp.digicert.com -v c:\repos\phil-test\Demo\bin\Demo.dll
```

dotnet info:

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

But as I said if I download the repo and package my-self and use what's packaged in the release folder with the exact same command it works.

**Comment by hikariuk** [comment] 2021-03-24 08:51
> But as I said if I download the repo and package my-self and use what's packaged in the release folder with the exact same command it works.

The package on the NuGet gallery was built against .NET Core 2.x, as far as I can tell. I think the problem is that .NET Core 5.x has breaking changes that stop some things working: I was running in to the same problem using AzureSignTool inside a Azure DevOps pipeline, which has also switched to 5 for agents. I ended doing the same as you and packaging my own build and deploying it to our artifact pipeline (which was a PITA itself).

This actually ended up helping me in the long run, because I've modified the tool slightly to include the option to skip already signed files.

**Comment by FabianGCZ** [comment] 2021-04-22 04:24
Got same issue, running "AzureSignTool sign -d <<value>>  -kvu <<value>> -kvi <<value>> -kvs <<value>>  -kvc <<value>> -kvt <<value>>  -tr "http://timestamp.digicert.com" -v "C:\Users\UserX\Setup.exe""
I narrowed the "issue" to be that somehow, the tool is not liking the '-kvt' parameter, if you run it without that it works as expected

**Comment by FabianGCZ** [comment] 2021-04-22 04:25
Got same issue, running "AzureSignTool sign -d <<value>>  -kvu <<value>> -kvi <<value>> -kvs <<value>>  -kvc <<value>> -kvt <<value>>  -tr "http://timestamp.digicert.com" -v "C:\Users\UserX\Setup.exe"" --> Nothing returned
I narrowed the "issue" to be that somehow, the tool is not liking the '-kvt' parameter, if you run it without that it works as expected

**Comment by FabianGCZ** [comment] 2021-04-22 04:25
Got same issue, running "AzureSignTool sign -d <<value>>  -kvu <<value>> -kvi <<value>> -kvs <<value>>  -kvc <<value>> -kvt <<value>>  -tr "http://timestamp.digicert.com" -v "C:\Users\UserX\Setup.exe"" --> **Nothing returned**
I narrowed the "issue" to be that somehow, the tool is not liking the '-kvt' parameter, if you run it without that it works as expected

**Comment by dpurge** [comment] 2021-07-30 10:01
Same issue, none of the parameter combinations mentioned in this issue works.

**Comment by vcsjones** [comment] 2021-09-21 16:21
Closing this as 3.0.0 has been release and should address the issue.

**Comment by riverar** [comment] 2021-09-21 16:22
@vcsjones Thanks Kevin!

**Closed by vcsjones** 2021-09-21 16:21 UTC
